/** The stopping-potential workbench's four readings, shown on the reader's detail setting.
 * Mirrored as the lq-08-data target in content/editorial/readings-owners/am-lq-08-photoelectric-va5a.yaml,
 * which the readings audit reads. Numbers are the workbench's accepted fit of the constructed
 * straight-trend example, and of the same record with a calibrated offset of 0 ± 0.01 V. */
export const PHOTOELECTRIC_DATA_CAPTION = Object.freeze({
  r0: "Enter stopping voltages measured at several frequencies, and the lab fits a straight line through them. The slope estimates Planck's constant divided by the electron's charge, but the line alone cannot give the surface's escape work unless you also know the instrument's voltage offset.",
  r1: "§8 of the light-quanta paper gives, for an electron that takes one quantum's energy and leaves the surface, Πε = (R/N)βν − P: the stopping potential Π rises in a straight line with the frequency ν, with a slope, (R/N)β/ε in Einstein's notation and h/e in ours, that should not depend on the substance. The workbench fits that line to a record: measured stopping voltage = slope × frequency + intercept. On the constructed example, five points from 500 to 900 THz, each with a standard uncertainty of 0.04 V, the fitted slope is 0.00399 ± 0.00013 V/THz. Multiplied by the elementary charge that is h = (6.39 ± 0.20) × 10^{−34} J·s, 3.5 percent below the defined 6.626 × 10^{−34}, a difference of about 1.2 standard errors. The reduced chi-square is 1.71 with 3 degrees of freedom: a diagnostic of how well the declared errors describe the scatter, not a verdict. The intercept, −1.49 V, mixes two things, the escape work per unit charge and a voltage offset common to every reading, such as the contact potential between the two electrodes. With the offset unknown, the workbench reports the work function as underdetermined. Enter an independently calibrated offset of 0 ± 0.01 V and it gives 1.49 ± 0.09 eV and a threshold of 374 ± 12 THz. The other two examples show what a fit can reveal: a curved trend leaves its residuals in a U shape with a reduced chi-square of 13, and a point with a 1 V uncertainty can sit 1.02 V off the line and still count for little. A straight line does not prove the quantum account by itself; it passes one test the account sets.",
  r2: "Write the single-quantum budget for one electron. A quantum of light carries the energy hν. Part of it, the escape work W, is spent getting the electron out of the surface, and the rest is the electron's kinetic energy. To stop the electron, the collector must be made negative enough that the electron's charge e times the voltage equals that kinetic energy, so eV = hν − W, or V = (h/e)ν − W/e. That is a straight line in ν with slope h/e. A real instrument adds a common voltage V_{off} to every reading, for instance the contact potential between two different metals, so the measured line is V = (h/e)ν + (V_{off} − W/e). Now fit the constructed record: 0.52, 0.85, 1.36, 1.66 and 2.11 V at 500, 600, 700, 800 and 900 THz, each with σ = 0.04 V. With equal uncertainties the weighted fit is ordinary least squares. The mean frequency is 700 THz and the mean voltage 1.30 V. The slope is the sum of (ν − 700)(V − 1.30) divided by the sum of (ν − 700)². The numerator is (−200)(−0.78) + (−100)(−0.45) + 0 + (100)(0.36) + (200)(0.81) = 156 + 45 + 36 + 162 = 399 V·THz, and the denominator is 40 000 + 10 000 + 0 + 10 000 + 40 000 = 100 000 THz², so the slope is 0.00399 V/THz. Its variance is σ² divided by the same sum, 0.0016/100 000 = 1.6 × 10^{−8}, a standard error of 0.000126 V/THz. The intercept is 1.30 − 0.00399 × 700 = −1.493 V. The residuals, data minus line, are 0.018, −0.051, 0.060, −0.039 and 0.012 V. The sum of their squares divided by σ² is 5.12, and divided by the 3 degrees of freedom left after fitting two numbers that is 1.71. A slope of 0.00399 V/THz is 3.99 × 10^{−15} V·s, and multiplied by e = 1.602 × 10^{−19} C it gives h = 6.39 × 10^{−34} J·s, against the defined 6.626 × 10^{−34}: the slopes differ by 0.00015 V/THz, about 1.2 standard errors. The intercept, −1.493 V, equals V_{off} − W/e. One equation cannot fix two unknowns: W/e = 1.49 V with no offset, or 1.99 V with an offset of +0.5 V, fits the same line equally well. Supplying V_{off} = 0 ± 0.01 V gives W/e = 1.493 V, so W = 1.49 eV, with an uncertainty of √(0.0903² + 0.01²) = 0.091 eV, and a threshold frequency W/h = 1.493/0.00399 = 374 THz. The threshold is where the corrected line crosses zero, not where the raw readings would, and the workbench carries the slope and intercept uncertainties and their covariance into its ±12 THz.",
  r3: "Einstein offered the line as a test he could not yet make. With the data then available he checked only the order of magnitude, about 4.3 volts for ν = 1.03 × 10^{15} s^{−1} with the escape work set to zero, against Lenard's results, and wrote that if the formula is right the curve must be a straight line whose slope does not depend on the substance. Richardson and Compton in 1912 found the maximum energy of the electrons rising roughly linearly with frequency, and Millikan's sodium and lithium measurements of 1916, which corrected for the contact potential between his electrodes, gave h ≈ 6.57 × 10^{−27} erg·s from the slope. Millikan still called the physical theory behind the equation untenable. The examples here are constructed, and a record loaded here is the reader's own, not a reviewed measurement.",
});
