/**
 * The wasm-bindgen glue of the pinned artifact, imported from its content-addressed
 * directory. The directory name is the first 16 hex of the module's sha256, and
 * pinnedArtifact.test.ts checks that it equals PINNED_ARTIFACT.hashPrefix. Moving the pin
 * means changing this path and pinnedArtifact.ts together.
 *
 * The glue is generated by wasm-bindgen 0.2.126 with --omit-default-module-path, so it never
 * fetches anything itself. The loader hands it bytes it has already verified.
 */
export * as pinnedGlue from "../../../public/wasm/fs-annus-diffusion/80a1f8fda6f69003/fs_annus_diffusion.js";
