import type { Metadata } from "next";
import { Formula } from "../../../components/edition/Formula.tsx";
export const metadata: Metadata = { title: "A first encounter with Brownian motion" };
export default function BrownianEncounter() {
  return <article className="reading encounter"><header><p className="eyebrow">Discover · No algebra required</p><h1>A particle wanders.<br />What should you measure?</h1><p className="lead">This is a route through a model’s argument, not a claim about Einstein’s private thought process. You can read every step without running a simulation.</p></header>
    <section><p className="step-number">01 / Choose a quantity</p><h2>Averages can hide motion.</h2><p>Imagine marking each particle’s starting point and looking again after one second. A movement to the right is positive; a movement to the left is negative. In a symmetric model, these signed displacements cancel on average even though the particles have spread out.</p><p>Before revealing the next step, choose what you would measure: signed displacement, absolute displacement, or squared displacement. The last two both retain information about the spread; neither is a test of whether a particle moved “correctly.”</p><details><summary>Why use the squared displacement?</summary><p>Squaring makes both leftward and rightward displacements positive. More importantly, independent steps with zero mean have a useful property: their mean squares add. Absolute displacements do not have that same additive rule. This gives the square a role in the derivation, not just a convenient sign.</p></details><p><a href="/lab/bm-01/">Compare signed means and mean squares in the tracer ensemble →</a></p></section>
    <section><p className="step-number">02 / Make a prediction</p><h2>Four times as long. Four times as far?</h2><p>Try three possibilities: no change, twice the typical displacement, or four times the typical displacement. A fixed-velocity model and an independent-step diffusion model do not make the same prediction.</p><details><summary>Follow the independent-step argument</summary><p>Four times the observation time gives four times the mean square displacement. Taking its square root gives twice the RMS displacement. The square grows linearly with time; its square root does not.</p><Formula latex={String.raw`\langle x^2\rangle=2Dt \qquad \lambda_x=\sqrt{2Dt}`} /><p>The laboratory’s one-second, ten-second and one-minute comparison is calculated from one accepted diffusion coefficient. It is not three independent measurements.</p></details><a href="/lab/bm-06/">Compare the observation times in the laboratory →</a></section>
    <section><p className="step-number">03 / Ask an interval question</p><h2>A curve’s height is not a probability.</h2><p>“How likely is the displacement to lie between −1 and +1 micrometres?” is an interval question. The model answers with an area, a dimensionless probability. The height of the density is measured per micrometre.</p><p>At the initial instant, all probability is at the starting point. An interval containing that point has probability one. At positive times, the continuous model assigns probability zero to one exact coordinate, but a finite interval can have positive probability.</p><details><summary>What happens in a more viscous liquid?</summary><p>Keeping temperature and radius fixed, doubling viscosity halves the diffusion coefficient. It does not halve the RMS displacement: the square-root relationship reduces that displacement by a factor of the square root of two.</p><p>Try changing viscosity from 1 to 2 mPa·s. The laboratory does not silently change viscosity when you edit temperature; they are separate declared inputs.</p></details></section>
    <aside className="notice"><h2>The model is not the evidence.</h2><p>Agreement between a numerical grid and an analytic curve checks their calculation under stated assumptions. It does not establish that real tracers obey those assumptions. Measurements, their uncertainty and their provenance are a separate part of the planned edition.</p></aside>
    <section><h2>Where this enters the paper</h2><p>The Brownian-motion paper’s §§4–5 connect irregular displacements to diffusion and then to a measurable displacement scale. The reviewed source text and aligned translation are not yet published here. This first encounter is newly authored explanatory material, not a substitute source face.</p><div className="actions"><a className="button" href="/lab/bm-06/">Investigate in the laboratory →</a><a href="/papers/">Back to the paper catalogue</a></div></section>
  </article>;
}
