/**
 * THE toolPopulation PATTERNS, CHECKED AGAINST REAL TOOL OUTPUT.
 *
 * Four records read a third-party tool's own wording instead of a census line this repository
 * prints: biome's "Checked N files", bun's "Ran N tests across", and tsc's `--diagnostics` summary.
 * The census already treats a pattern that does not match as a FINDING rather than a zero, which is
 * the right behaviour -- but a finding is only raised when the gate runs, and the gate runs in the
 * slowest lane there is. A pattern that stops matching after a tool's output changes should be
 * visible in a unit test, not after a fifteen-minute build.
 *
 * Each sample below is pasted from a real run and dated. They are deliberately NOT generated by
 * running the tools here: the point is to pin the WORDING, and a sample produced by the same tool
 * that is being matched could not detect the wording changing.
 */

import { describe, expect, test } from "bun:test";
import { CENSUS_RECORDS } from "./records.ts";

function patternFor(gate: string): { pattern: string; minimum: number } {
  const record = CENSUS_RECORDS.find((r) => r.gate === gate);
  if (!record?.toolPopulation) throw new Error(`${gate} declares no toolPopulation`);
  return { pattern: record.toolPopulation.pattern, minimum: record.toolPopulation.minimum };
}

/** tsc --noEmit --diagnostics, 2026-10-08, this repository. */
const TSC_OUTPUT = [
  "prepare lane: 46 generators ran, all clean.",
  "Files:              4913",
  "Lines:           1107622",
  "Identifiers:      1842301",
  "Symbols:           990218",
].join("\n");

/** biome check, 2026-10-08. */
const BIOME_OUTPUT = "Checked 3744 files in 1829ms. No fixes applied.";

/** bun test, 2026-10-08. */
const BUN_OUTPUT = "Ran 16938 tests across 1797 files. [454.27s]";

describe("each toolPopulation pattern captures the count from real output", () => {
  test("tsc's --diagnostics summary", () => {
    const { pattern, minimum } = patternFor("typecheck");
    const match = new RegExp(pattern).exec(TSC_OUTPUT);
    expect(match?.[1]).toBe("4913");
    // The floor is below the real count and above zero, or it would either refuse every run or
    // detect nothing.
    expect(minimum).toBeLessThan(4913);
    expect(minimum).toBeGreaterThan(0);
  });

  test("AND IT IS ANCHORED: the word `Files:` alone is not enough", () => {
    const { pattern } = patternFor("typecheck");
    // The exact prose an unanchored pattern would have matched. This is not hypothetical --
    // `Files:\s+(\d+)` matches it, which is why the stored pattern requires the `Lines:` that tsc
    // always prints directly beneath.
    expect(/Files:\s+(\d+)/.exec("Total Files: 12 somewhere")?.[1]).toBe("12");
    expect(new RegExp(pattern).exec("Total Files: 12 somewhere")).toBeNull();
    // And a word where a number belongs is not a count.
    expect(new RegExp(pattern).exec("Files: many\nLines: 3")).toBeNull();
  });

  test("the pattern survives output BEFORE it, because the gate runs generators first", () => {
    const { pattern } = patternFor("typecheck");
    // `bun run typecheck` is 46 generators and then tsc, so the summary is never the first line.
    // The census matches against the whole output with no multiline flag, which is exactly why a
    // `^`-anchored pattern would have been wrong here.
    expect(new RegExp(pattern).exec(TSC_OUTPUT)?.[1]).toBe("4913");
    expect(/^Files:\s+(\d+)/.exec(TSC_OUTPUT)).toBeNull();
  });

  test("biome's and bun's own summary lines", () => {
    for (const gate of ["lint", "format-check"]) {
      const { pattern } = patternFor(gate);
      expect(new RegExp(pattern).exec(BIOME_OUTPUT)?.[1]).toBe("3744");
      // The line biome printed in the incident AGENTS.md records first: a zero that read as clean.
      expect(new RegExp(pattern).exec("Checked 0 files in 1629µs")?.[1]).toBe("0");
    }
    const { pattern } = patternFor("unit-tests");
    expect(new RegExp(pattern).exec(BUN_OUTPUT)?.[1]).toBe("16938");
  });

  test("every record that declares a toolPopulation declares a usable floor", () => {
    const declaring = CENSUS_RECORDS.filter((r) => r.toolPopulation !== undefined);
    // Non-vacuity: if no record declared one, every assertion above would be unreachable and this
    // file would pass having checked nothing.
    expect(declaring.length).toBeGreaterThanOrEqual(4);
    for (const record of declaring) {
      const tool = record.toolPopulation;
      if (!tool) continue;
      // A minimum of 0 cannot detect anything, which the census says in its own type docs.
      expect(tool.minimum).toBeGreaterThan(0);
      expect(tool.why.length).toBeGreaterThan(40);
      // One capture group, or the census has nothing to read.
      expect(new RegExp(tool.pattern).source).toContain("(");
    }
  });
});
