import type { Metadata } from "next";
import "../lab/bm-07/kitchen/kitchen.css";
import "./kitchenGuide.css";
import {
  KITCHEN_COLUMNS,
  KITCHEN_METADATA_KEYS,
  KITCHEN_READER_COLUMNS,
} from "../../experiments/bm07/kitchen/schema.ts";
export const metadata: Metadata = {
  title: "Observe, measure, and question Brownian motion",
  description:
    "Watch a particle wander, measure its spread, and see what else a molecular count would need, starting from a practice file this page supplies. Stopping after watching is a complete result.",
};

const BLANK_ROW_IDS = [
  "row-1",
  "row-2",
  "row-3",
  "row-4",
  "row-5",
  "row-6",
  "row-7",
  "row-8",
] as const;

export default function KitchenGuide() {
  return (
    <div className="kitchen-guide">
      <header className="page-intro">
        <p className="eyebrow">An observation is already a result</p>
        <h1>
          Watch the wandering.
          <br />
          Keep the evidence.
        </h1>
        <p className="lead">
          A visible wandering track, a diffusion measurement and a molecular-number inference answer
          different questions. You can stop after observing without having failed to count anything.
        </p>
        {/* After the lead, not before it: the page used to open on this box, so the first thing a
            reader met was a list of materials they would not need, radioactive ones included,
            before being told what the page is for. */}
        <p className="callout-note">
          Start with the synthetic practice file this page supplies. You need no biological samples,
          powders, ultraviolet sources or radioactive materials.
        </p>
      </header>
      <section className="reading page-flush">
        <h2>Three questions, not three grades</h2>
        <table data-kitchen-stages>
          <caption>What each stage can establish</caption>
          <thead>
            <tr>
              <th scope="col">Stage</th>
              <th scope="col">Question</th>
              <th scope="col">Supported conclusion</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">Observe</th>
              <td>Does this particle wander?</td>
              <td>
                A documented qualitative track. This is a complete observational result, not a
                molecular count.
              </td>
            </tr>
            <tr>
              <th scope="row">Measure</th>
              <td>What spread is compatible with these positions?</td>
              <td>
                A model-dependent diffusion estimate with explicit timing, calibration, click error
                and selection limits.
              </td>
            </tr>
            <tr>
              <th scope="row">Infer</th>
              <td>What independent inputs permit a molecular-number estimate?</td>
              <td>
                A conditional inference only after radius, viscosity, temperature and constant
                provenance are established.
              </td>
            </tr>
          </tbody>
        </table>
        <p>
          The quantitative model depends on particle size, shape, wall proximity, viscosity, drift
          and optical resolution. A known-size particle or a dataset with independent calibration
          and physical measurements is a better quantitative starting point than guessing those
          quantities. The supplied track is synthetic practice, not a real observation sequence.
        </p>
        <div className="actions">
          <a className="button" href="/lab/bm-07/kitchen/">
            Analyze a local CSV (requires JavaScript)
          </a>
          <a href="/edition/kitchen/practice.csv" download>
            Download synthetic practice observations
          </a>
        </div>
        <h2>Start with the supplied record</h2>
        <p>
          The practice file is generated by the camera model. It contains a particle track, separate
          stationary-feature clicks and declared calibration. Open the local analyzer and choose
          “Analyze synthetic practice data.” No worker starts merely because the page loaded. The
          radius is deliberately not supplied: observe the ambiguity before declaring an independent
          measurement.
        </p>
        <h2>Bring observations without rewriting them</h2>
        <p>
          Use positions measured in the original source-image pixels and record the actual frame
          timestamps. Give each particle its own object identity. Retain losses and their reasons,
          and explicitly decide whether a reacquired label is the same object or a new one. Never
          fill a gap with an invented measurement. Mark any interpolation as interpolated; it is not
          used as a measured point.
        </p>
        <p>
          Record repeated clicks on one stationary feature under the same localization-error
          assumptions. A blank exposure is unknown, not a zero-duration exposure. Independently
          calibrated axes keep separate scales. Calibration declarations are not verified merely
          because they parse.
        </p>
        <h2>Read the uncertainty before the number</h2>
        <p>
          The analyzer uses disjoint frame pairs, fits constant drift and includes stationary-click
          sampling uncertainty. Unsupported timing, missing camera information and ambiguous
          calibration can withhold an interval. Excluding rows preserves them and their reasons but
          withholds interval coverage after manual sample selection. Lost particles can be
          informative: an interval based on the survivors does not correct that selection.
        </p>
        <p>
          A radius inferred from these same displacements with an assumed molecular number is
          circular. An independent radius permits a conditional calculation, but this preview does
          not combine radius, calibration, temperature, viscosity and gas-constant uncertainty into
          a single coverage claim. A narrow conditional interval is not a narrow total uncertainty.
        </p>
        <h2>Keep your record</h2>
        <p>
          The analyzer reads the selected file in this browser. Its analysis worker has no upload or
          persistence step. Export the accepted observations to reopen them later, and export the
          analysis to retain its source identity, assumptions and results. Closing or reloading the
          page discards the in-memory session. Clearing one laboratory does not delete downloaded
          files or another placement’s data.
        </p>
        <p>
          The analyzer now supports bounded local video annotation and calibration. It does not
          automatically save sessions or supply a reviewed microscope protocol or licensed real
          sequence.
        </p>
        <h2 id="worksheet">A shared-schema classroom worksheet</h2>
        <p>
          <a href="/edition/kitchen/worksheet.txt" download>
            Download the blank worksheet as text
          </a>
          . The column lists and metadata keys below come from the same module as the importer.
          Complete all declarations and observation rows before importing. Unknown optional
          measurements may remain blank; missing declarations are different from unknown values.
        </p>
        <details>
          <summary>Reader-filled columns and blank observation rows</summary>
          <section
            className="table-scroll kitchen-worksheet"
            aria-label="Blank observation worksheet"
            // biome-ignore lint/a11y/noNoninteractiveTabindex: a scrollable region must be focusable
            tabIndex={0}
          >
            <table>
              <caption>
                Reader-filled columns in import order; the exporter supplies schema_version
              </caption>
              <thead>
                <tr>
                  {KITCHEN_READER_COLUMNS.map((k) => (
                    <th key={k} scope="col">
                      {k}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {BLANK_ROW_IDS.map((rowId) => (
                  <tr key={rowId}>
                    {KITCHEN_READER_COLUMNS.map((k) => (
                      <td key={k}>________</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        </details>
        <details>
          <summary>Required CSV header and metadata declaration keys</summary>
          <p>
            The complete import header includes the schema-version column. Every observation row
            starts with 2.
          </p>
          <section
            className="kitchen-schema"
            aria-label="Required CSV header and metadata declaration keys"
            // biome-ignore lint/a11y/noNoninteractiveTabindex: a scrollable region must be focusable
            tabIndex={0}
          >
            <pre>{KITCHEN_COLUMNS.join(",")}</pre>
          </section>
          <dl>
            {KITCHEN_METADATA_KEYS.map((k) => (
              <div key={k}>
                <dt>
                  <code>{k}</code>
                </dt>
                <dd>Record the value or an explicitly permitted blank.</dd>
              </div>
            ))}
          </dl>
          <p>
            Preserve the metadata comments in the practice CSV as a format example. Replace the
            synthetic values only with your actual declarations; a file’s declared origin is not
            independently verified.
          </p>
        </details>
        <div className="actions">
          <a href="/lab/bm-08/">Open the camera laboratory</a>
          <a href="/papers/brownian-motion/#arg-bm-inference">
            Return to the Brownian inference argument
          </a>
        </div>
      </section>
    </div>
  );
}
