import type { Quantity, QuantityRegistry } from "./quantities.ts";

/**
 * Modern teaching notation for the light-quanta paper's explanation-face formulas. Every id is a
 * canonical one from content/quantities/ (radiation.yaml, constants.yaml); a glyph is never a key.
 * The formulas these serve are written in modern notation (h, k_B, Phi), so the definitions say
 * where the 1905 paper wrote the same thing differently. Dimension order is length, mass, time,
 * temperature, current, amount.
 */
const energy = ["2", "1", "-2", "0", "0", "0"] as const;
const action = ["2", "1", "-1", "0", "0", "0"] as const;
const rate = ["0", "0", "-1", "0", "0", "0"] as const;
const charge = ["0", "0", "1", "0", "1", "0"] as const;
const potential = ["2", "1", "-3", "0", "-1", "0"] as const;
const temperature = ["0", "0", "0", "1", "0", "0"] as const;
const entropyPerKelvin = ["2", "1", "-2", "-1", "0", "0"] as const;
const spectralDensity = ["-1", "1", "-1", "0", "0", "0"] as const;
const alphaDimension = ["-1", "1", "2", "0", "0", "0"] as const;
const betaDimension = ["0", "0", "1", "1", "0", "0"] as const;
const molarGas = ["2", "1", "-2", "-1", "0", "-1"] as const;
const perAmount = ["0", "0", "0", "0", "0", "-1"] as const;
const speed = ["1", "0", "-1", "0", "0", "0"] as const;
const count = ["0", "0", "0", "0", "0", "0"] as const;
const energyDensity = ["-1", "1", "-2", "0", "0", "0"] as const;
const entropyDensity = ["-1", "1", "-1", "-1", "0", "0"] as const;
const volume = ["3", "0", "0", "0", "0", "0"] as const;
function quantity(
  id: string,
  name: string,
  glyph: string,
  dimension: readonly string[],
  unit: string,
  semanticKind: string,
  role: Quantity["role"],
  definition: string,
): Quantity {
  return Object.freeze({
    id,
    name,
    glyph,
    dimension: Object.freeze([...dimension]),
    unit,
    displayUnit: unit,
    displayPower: 0,
    semanticKind,
    role,
    definition,
  });
}
export const LIGHT_QUANTA_QUANTITIES: QuantityRegistry = Object.freeze(
  Object.fromEntries(
    [
      quantity(
        "maxKineticEnergy",
        "Largest kinetic energy of an emitted electron",
        "K_{\\mathrm{max}}",
        energy,
        "J",
        "photoelectron-maximum-kinetic-energy",
        "result",
        "The most energy of motion an electron can carry out of the metal in the one-quantum model: one quantum's energy less the escape work. An electron that loses energy on the way out leaves with less.",
      ),
      quantity(
        "planckConstant",
        "Planck's constant",
        "h",
        action,
        "J s",
        "planck-constant",
        "constant",
        "The constant that sets one quantum's energy, h times the frequency. The 1905 paper writes the same quantum as R beta nu over N, from the constants of Planck's radiation formula; h is the later name for R beta over N.",
      ),
      quantity(
        "frequency",
        "Frequency of the light",
        "\\nu",
        rate,
        "Hz",
        "cyclic-frequency",
        "input",
        "The cyclic frequency of the incident light, in cycles per second. It sets the energy of each quantum; the light's power sets how many arrive.",
      ),
      quantity(
        "workFunction",
        "Escape work",
        "\\Phi",
        energy,
        "J",
        "work-function",
        "input",
        "The least energy an electron must spend to leave the metal's surface. Einstein's section 8 calls it P. A value used in an example here is hypothetical, not a measured figure for a named metal.",
      ),
      quantity(
        "thresholdFrequency",
        "Threshold frequency",
        "\\nu_0",
        rate,
        "Hz",
        "photoelectric-threshold-frequency",
        "result",
        "The lowest frequency whose single quantum can pay the escape work: the escape work divided by h. Below it the model emits no electron, however bright the light.",
      ),
      quantity(
        "elementaryCharge",
        "Charge of one electron",
        "e",
        charge,
        "C",
        "elementary-charge-magnitude",
        "constant",
        "The size of one electron's charge. Multiplied by a potential difference it gives an energy, which is how a stopping potential measures the fastest electron's energy.",
      ),
      quantity(
        "stoppingPotentialMagnitude",
        "Stopping potential",
        "V_{\\mathrm{s}}",
        potential,
        "V",
        "stopping-potential-magnitude",
        "input",
        "The size of the retarding potential that just stops the fastest electrons from reaching the collector. It is measured, and its product with the electron's charge is an energy.",
      ),
      quantity(
        "frequencyEnergyDensity",
        "Spectral energy density",
        "u_\\nu",
        spectralDensity,
        "J s m^-3",
        "frequency-basis-spectral-energy-density",
        "input",
        "Radiation energy per unit volume per unit frequency interval, the quantity the paper writes rho_nu. It is a density on the frequency axis, so it cannot be read off a wavelength plot without converting.",
      ),
      quantity(
        "wienConstantAlpha",
        "Spectral constant A",
        "A",
        alphaDimension,
        "J s^4 m^-3",
        "wien-alpha",
        "constant",
        "The constant in front of the Wien spectrum, fitted to measured radiation. The paper writes it alpha; it carries whatever units make A nu cubed a spectral energy density.",
      ),
      quantity(
        "wienConstantBeta",
        "Spectral constant B",
        "B",
        betaDimension,
        "K s",
        "wien-beta",
        "constant",
        "The constant in the exponent of the Wien spectrum; B nu over T is a pure number. The paper writes it beta, and in modern terms it is h over k_B.",
      ),
      quantity(
        "temperature",
        "Temperature of the radiation",
        "T",
        temperature,
        "K",
        "absolute-temperature",
        "input",
        "The absolute temperature of the black-body radiation, in kelvin.",
      ),
      quantity(
        "boltzmannConstant",
        "Boltzmann's constant",
        "k_B",
        entropyPerKelvin,
        "J/K",
        "boltzmann-constant",
        "constant",
        "The gas constant divided by Avogadro's number, R over N, which is how the 1905 paper writes it. The name k_B came later.",
      ),
      quantity(
        "radiationEnergy",
        "Radiation energy in the band",
        "E",
        energy,
        "J",
        "band-radiation-energy",
        "input",
        "The energy of the radiation inside a fixed narrow band of frequencies, held fixed while the volume changes.",
      ),
      quantity(
        "effectiveIndependentCount",
        "Effective number of independent points",
        "n_{\\mathrm{eff}}",
        count,
        "1",
        "effective-independent-count",
        "result",
        "The number of independent points a gas would need to show the same entropy change as the radiation. It is read off by comparison; it is not a count of anything observed.",
      ),
      quantity(
        "molarGasConstant",
        "Gas constant",
        "R",
        molarGas,
        "J/(K mol)",
        "molar-gas-constant",
        "constant",
        "The gas constant per gram-molecule, known in 1905 from gas measurements.",
      ),
      quantity(
        "avogadroConstant",
        "Avogadro's number",
        "N_A",
        perAmount,
        "1/mol",
        "avogadro-constant",
        "constant",
        "The number of molecules in a gram-molecule. The paper solves for it from the constants of Planck's radiation formula; the value it gets is an estimate from those constants.",
      ),
      quantity(
        "speedOfLight",
        "Speed of light",
        "c",
        speed,
        "m/s",
        "speed-of-light",
        "constant",
        "The speed of light in empty space, which the paper writes L.",
      ),
      quantity(
        "incidentFrequency",
        "Frequency of the absorbed light",
        "\\nu_1",
        rate,
        "Hz",
        "fluorescence-incident-frequency",
        "input",
        "The frequency of the light the fluorescent body takes in.",
      ),
      quantity(
        "emittedFrequency",
        "Frequency of the emitted light",
        "\\nu_2",
        rate,
        "Hz",
        "fluorescence-emitted-frequency",
        "result",
        "The frequency of the light the body gives out. Stokes's rule, which the paper explains, says it is no higher than the incident frequency.",
      ),
      quantity(
        "ionizationEnergyPerMolecule",
        "Energy to ionize one molecule",
        "I",
        energy,
        "J",
        "ionization-energy-per-molecule",
        "input",
        "The least energy that frees an electron from one gas molecule. The paper's section 9 states it per gram-equivalent and prints that work J.",
      ),
      quantity(
        "absorbedLightEnergy",
        "Light energy absorbed",
        "L",
        energy,
        "J",
        "absorbed-light-energy",
        "input",
        "The light energy the gas absorbs. The paper's section 9 prints it L.",
      ),
      quantity(
        "ionCount",
        "Number of ionized molecules",
        "n_{\\mathrm{ions}}",
        count,
        "1",
        "ionized-molecule-count",
        "result",
        "How many molecules the light ionizes, counted one by one. The paper's j counts gram-molecules, bounded by L over R beta nu; this is the same bound read molecule by molecule.",
      ),
      quantity(
        "independentPointCount",
        "Number of independent points",
        "n",
        count,
        "1",
        "independent-point-count",
        "input",
        "The number of independently moving points in the gas the radiation is compared with, section 5's kinetic-theory model.",
      ),
      quantity(
        "volumeRatio",
        "Volume ratio",
        "f",
        count,
        "1",
        "volume-ratio",
        "input",
        "The factor by which the volume changes, V over V_0. A pure number.",
      ),
      quantity(
        "configurationProbability",
        "Probability of the configuration",
        "W",
        count,
        "1",
        "configuration-probability",
        "result",
        "Section 5's W: the probability that, at one instant, all n independent points are in the fraction f of the volume. A pure number between 0 and 1.",
      ),
      quantity(
        "gasEntropyChange",
        "Entropy change of the gas",
        "\\Delta S_{\\mathrm{gas}}",
        entropyPerKelvin,
        "J/K",
        "gas-entropy-change",
        "result",
        "The entropy change of n independent points when their volume changes by the factor f.",
      ),
      quantity(
        "radiationEntropyChange",
        "Entropy change of the radiation",
        "\\Delta S_{\\mathrm{rad}}",
        entropyPerKelvin,
        "J/K",
        "radiation-entropy-change",
        "result",
        "The entropy change of dilute radiation of fixed energy and band when its volume changes by the factor f. Section 4's result.",
      ),
      quantity(
        "energyDensityBelowCutoff",
        "Energy density below the cutoff",
        "U",
        energyDensity,
        "J/m^3",
        "cutoff-energy-density",
        "result",
        "The radiation energy per cubic metre in all frequencies from zero up to the cutoff; U(nu_c) is its value at cutoff nu_c.",
      ),
      quantity(
        "radiationEntropy",
        "Radiation entropy",
        "S",
        entropyPerKelvin,
        "J/K",
        "radiation-entropy",
        "result",
        "The entropy of the radiation in the whole volume; S(V) is its value when the radiation fills volume V.",
      ),
      quantity(
        "volume",
        "Volume",
        "V",
        volume,
        "m^3",
        "volume",
        "input",
        "The volume the radiation fills; V_0 is the volume it is compared with.",
      ),
      quantity(
        "bandwidth",
        "Width of the band",
        "\\Delta\\nu",
        rate,
        "Hz",
        "bandwidth",
        "input",
        "The width of the narrow frequency band the radiation occupies.",
      ),
      quantity(
        "spectralEntropyDensity",
        "Spectral entropy density",
        "s_\\nu",
        entropyDensity,
        "J s/(K m^3)",
        "spectral-entropy-density",
        "result",
        "Radiation entropy per cubic metre per unit of frequency. The paper writes it phi.",
      ),
      quantity(
        "entropyDensityConstant",
        "Integration constant",
        "C",
        entropyDensity,
        "J s/(K m^3)",
        "entropy-density-constant",
        "input",
        "The constant that integrating the entropy relation leaves; C(nu) may depend on frequency. The paper's boundary condition sets it to zero.",
      ),
      quantity(
        "entropyFromUnfixedConstant",
        "Entropy from an unfixed constant",
        "\\Delta S_C",
        entropyPerKelvin,
        "J/K",
        "unfixed-constant-entropy",
        "result",
        "The entropy an unfixed constant C(nu) would add to the comparison of two volumes.",
      ),
    ].map((q) => [q.id, q]),
  ),
);
