import type { Quantity, QuantityRegistry } from "./quantities.ts";

/** Modern teaching notation only. These identities already exist in content/quantities/.
 * Body energies and the additive offset are symbolic: no rest-energy law is assumed.
 * Dimension order is length, mass, time, temperature, current, amount.
 */
const energy = ["2", "1", "-2", "0", "0", "0"] as const;
const mass = ["0", "1", "0", "0", "0", "0"] as const;
const speed = ["1", "0", "-1", "0", "0", "0"] as const;
const ratio = ["0", "0", "0", "0", "0", "0"] as const;
function quantity(
  id: string,
  name: string,
  glyph: string,
  dimension: readonly string[],
  unit: string,
  semanticKind: string,
  role: Quantity["role"],
  definition: string,
): Quantity {
  return Object.freeze({
    id,
    name,
    glyph,
    dimension: Object.freeze([...dimension]),
    unit,
    displayUnit: unit,
    displayPower: 0,
    semanticKind,
    role,
    definition,
  });
}
export const MASS_ENERGY_QUANTITIES: QuantityRegistry = Object.freeze(
  Object.fromEntries(
    [
      quantity(
        "emittedEnergyRestFrame",
        "Emitted energy in the body's rest frame",
        "L",
        energy,
        "J",
        "rest-frame-emitted-energy",
        "input",
        "Total energy of the two opposite light pulses in the body's rest frame. It is an input, not the body's total energy or an assigned rest energy.",
      ),
      quantity(
        "bodyEnergyRestBefore",
        "Body energy before emission, rest description",
        "E_0",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The body's energy before emission in the frame in which the body is at rest. Its absolute value is deliberately unknown; it is not initialized as mass times c squared.",
      ),
      quantity(
        "bodyEnergyRestAfter",
        "Body energy after emission, rest description",
        "E_1",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The body's remaining energy after emission in the same rest description. Radiation that has left the body is outside this body's account.",
      ),
      quantity(
        "bodyEnergyMovingBefore",
        "Body energy before emission, moving description",
        "H_0",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The same body's pre-emission energy in an inertial frame moving relative to it. H and E label different frame descriptions, not two different emission events.",
      ),
      quantity(
        "bodyEnergyMovingAfter",
        "Body energy after emission, moving description",
        "H_1",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The same body's post-emission energy in the moving description. The observer's speed is held fixed between the before and after accounts.",
      ),
      quantity(
        "kineticEnergyBefore",
        "Energy of motion before emission",
        "K_0",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The body's energy of motion before emission, relative to the moving observer. Its absolute value is not supplied by this derivation.",
      ),
      quantity(
        "kineticEnergyAfter",
        "Energy of motion after emission",
        "K_1",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The body's energy of motion after emission, at the same observer speed. A difference can be determined without choosing either absolute kinetic energy.",
      ),
      quantity(
        "additiveEnergyConstant",
        "Unchanged additive energy offset",
        "C",
        energy,
        "J",
        "ledger-energy",
        "input",
        "The additive offset in H minus E equals K plus C. The same C before and after emission is an explicit premise, not something derived by subtracting the ledgers.",
      ),
      quantity(
        "frameSpeed",
        "Signed observer speed",
        "v",
        speed,
        "m/s",
        "frame-speed",
        "input",
        "The signed speed of the moving description relative to the body's rest frame. Its magnitude is strictly less than the speed of light and is unchanged across the emission.",
      ),
      quantity(
        "speedOfLight",
        // The quantity's name, as the registry has it. "In SI" belonged to the value's constant set,
        // and on Einstein's printed faces it named his V, in Gaussian units (dispatch 233).
        "Speed of light",
        "c",
        speed,
        "m/s",
        "speed-of-light",
        "constant",
        "The modern SI speed of light. This c belongs to explicitly modern teaching notation; a normalized c equals one is not an SI measurement.",
      ),
      quantity(
        "lorentzFactor",
        "Lorentz factor",
        "\\gamma",
        ratio,
        "1",
        "lorentz-factor",
        "result",
        "One divided by the square root of one minus v squared over c squared. Modern gamma is not modern beta; Einstein's beta in paper 3 denotes the factor, not the speed ratio.",
      ),
      quantity(
        "kineticEnergyDifference",
        "Exact drop in energy of motion",
        "\\Delta K",
        energy,
        "J",
        "kinetic-energy-difference",
        "result",
        "K before minus K after under the unchanged-offset premise. Positive means that the body loses energy of motion at the same observer speed; it is not a signed after-minus-before change.",
      ),
      quantity(
        "quadraticKineticDifference",
        "Quadratic energy-drop approximation",
        "Q",
        energy,
        "J",
        "quadratic-kinetic-energy",
        "result",
        "The leading second-order term, one half L times v squared over c squared. This is not the exact finite-speed drop.",
      ),
      quantity(
        "finiteSpeedMassProxy",
        "Finite-speed mass proxy",
        "m_{\\mathrm{proxy}}",
        mass,
        "kg",
        "finite-speed-mass-proxy",
        "result",
        "Twice the exact kinetic-energy drop divided by v squared. This speed-dependent proxy is not the mass decrease; at zero speed the quotient is not applicable.",
      ),
      quantity(
        "inertialMassDecrease",
        "Positive inertial mass decrease",
        "m_{\\mathrm{loss}}",
        mass,
        "kg",
        "limiting-mass-coefficient",
        "result",
        "The positive mass decrease identified from the low-speed coefficient using Newtonian kinetic energy. Its identification is conditional and comes from an analytic limit, not a finite-speed proxy.",
      ),
      quantity(
        "massChangeSigned",
        "Signed change in body mass",
        "\\Delta m",
        mass,
        "kg",
        "signed-mass-change",
        "result",
        "Mass after minus mass before. Emission of positive energy L gives a negative signed change, unlike the positive mass-decrease magnitude.",
      ),
      quantity(
        "lightComplexEnergyStationary",
        "Energy of one light pulse, rest frame",
        "e",
        energy,
        "J",
        "light-energy-stationary",
        "input",
        "The energy of one emitted light pulse measured in the body's rest frame. Paper 4 takes its transformation from paper 3, section 8.",
      ),
      quantity(
        "lightComplexEnergyMoving",
        "Energy of one light pulse, moving frame",
        "e'",
        energy,
        "J",
        "light-energy-moving",
        "result",
        "The same pulse's energy measured from the frame in which the body moves at speed v.",
      ),
      quantity(
        "speedRatio",
        "Speed as a fraction of light speed",
        "\\beta",
        ratio,
        "1",
        "speed-ratio",
        "input",
        "v divided by c. Modern notation; it is not the beta of paper 3, which is the factor gamma.",
      ),
      quantity(
        "emissionAngle",
        "Emission angle",
        "\\varphi",
        ratio,
        "rad",
        "emission-angle",
        "input",
        "The angle between a pulse's direction and the direction of the body's motion.",
      ),
      quantity(
        "bodyMassBefore",
        "Body mass before emission",
        "m_0",
        mass,
        "kg",
        "body-mass",
        "input",
        "The body's inertial mass before it emits the light.",
      ),
      quantity(
        "bodyMassAfter",
        "Body mass after emission",
        "m_1",
        mass,
        "kg",
        "body-mass",
        "input",
        "The body's inertial mass after it has emitted the light.",
      ),
    ].map((q) => [q.id, q]),
  ),
);
