import type { Quantity, QuantityRegistry } from "./quantities.ts";

/**
 * Modern teaching notation for the relativity paper's explanation-face formulas. Every entry
 * reuses a canonical id from content/quantities/ (kinematics.yaml, constants.yaml), never a
 * glyph: paper 3's beta is the modern gamma, V is the speed of light, and tau is the moving
 * frame's time coordinate, not proper time. So the modern Delta tau below binds
 * properTimeElapsed, and the moving frame's time binds coordinateTimeMoving, whatever letter a
 * formula uses for either.
 *
 * Sections 1 to 10. The frame speed and the velocity components along x share
 * one semantic kind, velocity-along-x, because the composition law subtracts one from the other. Dimension order is length, mass, time, temperature,
 * current, amount.
 */
const time = ["0", "0", "1", "0", "0", "0"] as const;
const length = ["1", "0", "0", "0", "0", "0"] as const;
const speed = ["1", "0", "-1", "0", "0", "0"] as const;
const ratio = ["0", "0", "0", "0", "0", "0"] as const;
const frequency = ["0", "0", "-1", "0", "0", "0"] as const;
const energy = ["2", "1", "-2", "0", "0", "0"] as const;
const energyDensity = ["-1", "1", "-2", "0", "0", "0"] as const;
const volume = ["3", "0", "0", "0", "0", "0"] as const;
const chargeDensity = ["-3", "0", "1", "0", "1", "0"] as const;
const currentDensity = ["-2", "0", "0", "0", "1", "0"] as const;
const force = ["1", "1", "-2", "0", "0", "0"] as const;
const acceleration = ["1", "0", "-2", "0", "0", "0"] as const;
const mass = ["0", "1", "0", "0", "0", "0"] as const;
const charge = ["0", "0", "1", "0", "1", "0"] as const;
const potential = ["2", "1", "-3", "0", "-1", "0"] as const;
const magneticField = ["0", "1", "-2", "0", "-1", "0"] as const;
const electricField = ["1", "1", "-3", "0", "-1", "0"] as const;
function quantity(
  id: string,
  name: string,
  glyph: string,
  dimension: readonly string[],
  unit: string,
  semanticKind: string,
  role: Quantity["role"],
  definition: string,
): Quantity {
  return Object.freeze({
    id,
    name,
    glyph,
    dimension: Object.freeze([...dimension]),
    unit,
    displayUnit: unit,
    displayPower: 0,
    semanticKind,
    role,
    definition,
  });
}
export const SPECIAL_RELATIVITY_QUANTITIES: QuantityRegistry = Object.freeze(
  Object.fromEntries(
    [
      quantity(
        "signalDepartureTimeA",
        "Departure time at A",
        "t_A",
        time,
        "s",
        "clock-reading",
        "input",
        "The reading of clock A when the light signal leaves A for B.",
      ),
      quantity(
        "signalReflectionTimeB",
        "Reflection time at B",
        "t_B",
        time,
        "s",
        "clock-reading",
        "result",
        "The reading clock B is to show when the signal is reflected there. The synchronization rule assigns it; nothing measures it independently of that rule.",
      ),
      quantity(
        "signalReturnTimeA",
        "Return time at A",
        "t_{A,\\mathrm{return}}",
        time,
        "s",
        "clock-reading",
        "input",
        "The reading of clock A when the signal reflected at B arrives back at A.",
      ),
      quantity(
        "coordinatePositionStationary",
        "Position in the stationary system",
        "x",
        length,
        "m",
        "coordinate",
        "input",
        "An event's position along the direction of motion, as the stationary system assigns it.",
      ),
      quantity(
        "coordinatePositionMoving",
        "Position in the moving system",
        "x'",
        length,
        "m",
        "coordinate",
        "result",
        "The same event's position along the direction of motion, as the moving system assigns it.",
      ),
      quantity(
        "coordinateTimeStationary",
        "Time in the stationary system",
        "t",
        time,
        "s",
        "coordinate",
        "input",
        "An event's time as the stationary system's synchronized clocks assign it.",
      ),
      quantity(
        "coordinateTimeMoving",
        "Time in the moving system",
        "t'",
        time,
        "s",
        "coordinate",
        "result",
        "The same event's time as the moving system's synchronized clocks assign it. It is a coordinate, not the proper time of any one clock.",
      ),
      quantity(
        "eventSeparationSpatial",
        "Distance between two events",
        "\\Delta x",
        length,
        "m",
        "event-separation",
        "input",
        "The difference in position of two events along the direction of motion, in the stationary system.",
      ),
      quantity(
        "eventSeparationTemporalStationary",
        "Time between two events, stationary system",
        "\\Delta t",
        time,
        "s",
        "event-separation",
        "input",
        "The difference in time of two events as the stationary system's clocks assign it.",
      ),
      quantity(
        "eventSeparationTemporalMoving",
        "Time between two events, moving system",
        "\\Delta t'",
        time,
        "s",
        "event-separation",
        "result",
        "The difference in time of the same two events as the moving system's clocks assign it.",
      ),
      quantity(
        "properTimeElapsed",
        "Time a moving clock records",
        "\\Delta\\tau",
        time,
        "s",
        "proper-time",
        "input",
        "The time elapsed on one clock between two of its own ticks, both at the same place in the clock's rest frame. This is the modern proper time, not the paper's tau, which is the moving frame's time coordinate.",
      ),
      quantity(
        "lengthProper",
        "Rest length",
        "L_0",
        length,
        "m",
        "length",
        "input",
        "A rod's length measured by a ruler at rest with the rod.",
      ),
      quantity(
        "lengthMeasuredStationary",
        "Length of the moving rod",
        "L",
        length,
        "m",
        "length",
        "result",
        "The distance between the moving rod's two ends, located at the same time in the stationary system.",
      ),
      quantity(
        "frameSpeed",
        "Speed of the moving system",
        "v",
        speed,
        "m/s",
        "velocity-along-x",
        "input",
        "The speed of the moving system relative to the stationary one, along x. Its magnitude is less than the speed of light.",
      ),
      quantity(
        "speedOfLight",
        // The quantity's name, as the registry has it. "In SI" belonged to the value's constant set,
        // and on Einstein's printed faces it named his V, in Gaussian units (dispatch 233).
        "Speed of light",
        "c",
        speed,
        "m/s",
        "speed-of-light",
        "constant",
        "The modern SI speed of light, the paper's V. The same in both systems by the principle the paper adopts in section 2.",
      ),
      quantity(
        "lorentzFactor",
        "Lorentz factor",
        "\\gamma",
        ratio,
        "1",
        "lorentz-factor",
        "result",
        "One divided by the square root of one minus v squared over c squared. The paper writes this factor as beta; modern notation calls it gamma.",
      ),
      quantity(
        "transformationCoefficientA",
        "Undetermined scale",
        "a(v)",
        ratio,
        "1",
        "transformation-coefficient",
        "input",
        "The common factor the light conditions leave undetermined. Symmetry and continuity then fix it as gamma.",
      ),
      quantity(
        "dopplerFactor",
        "Frequency ratio",
        "q",
        ratio,
        "1",
        "doppler-factor",
        "result",
        "The moving system's frequency over the stationary system's, for the same light: gamma times one minus v over c times the cosine of the light's angle to the motion.",
      ),
      quantity(
        "waveFrequencyStationary",
        "Frequency, stationary system",
        "\\nu",
        frequency,
        "Hz",
        "wave-frequency",
        "input",
        "How many wave crests pass per second, counted in the stationary system.",
      ),
      quantity(
        "waveFrequencyMoving",
        "Frequency, moving system",
        "\\nu'",
        frequency,
        "Hz",
        "wave-frequency",
        "result",
        "The same light's frequency, counted in the moving system.",
      ),
      quantity(
        "waveFrequencyReflectedStationary",
        "Reflected frequency",
        "\\nu_{\\mathrm{ref}}",
        frequency,
        "Hz",
        "wave-frequency",
        "result",
        "The frequency of the light after reflection from the moving mirror, counted in the stationary system.",
      ),
      quantity(
        "propagationAngleStationary",
        "Angle to the motion, stationary system",
        "\\varphi",
        ratio,
        "rad",
        "propagation-angle",
        "input",
        "The angle between the light's direction and the direction of motion, in the stationary system.",
      ),
      quantity(
        "propagationAngleMoving",
        "Angle to the motion, moving system",
        "\\varphi'",
        ratio,
        "rad",
        "propagation-angle",
        "result",
        "The same light's angle to the direction of motion, in the moving system.",
      ),
      quantity(
        "lightEnergyDensityStationary",
        "Energy density, stationary system",
        "u",
        energyDensity,
        "J/m^3",
        "energy-density",
        "input",
        "The light's energy per cubic metre, in the stationary system.",
      ),
      quantity(
        "lightEnergyDensityMoving",
        "Energy density, moving system",
        "u'",
        energyDensity,
        "J/m^3",
        "energy-density",
        "result",
        "The same light's energy per cubic metre, in the moving system.",
      ),
      quantity(
        "lightComplexVolumeStationary",
        "Volume of the light packet, stationary system",
        "V_{\\mathrm{packet}}",
        volume,
        "m^3",
        "light-complex-volume",
        "input",
        "The volume of a bounded piece of light, its surface moving with the light, at one time of the stationary system.",
      ),
      quantity(
        "lightComplexVolumeMoving",
        "Volume of the light packet, moving system",
        "V_{\\mathrm{packet}}'",
        volume,
        "m^3",
        "light-complex-volume",
        "result",
        "The volume of the same piece of light at one time of the moving system.",
      ),
      quantity(
        "lightComplexEnergyStationary",
        "Energy of the light packet, stationary system",
        "E",
        energy,
        "J",
        "light-complex-energy",
        "input",
        "The whole energy of the bounded piece of light, in the stationary system.",
      ),
      quantity(
        "lightComplexEnergyMoving",
        "Energy of the light packet, moving system",
        "E'",
        energy,
        "J",
        "light-complex-energy",
        "result",
        "The whole energy of the same piece of light, in the moving system. The mass-energy paper uses exactly this ratio.",
      ),
      quantity(
        "chargeDensityStationary",
        "Charge density, stationary system",
        "\\rho",
        chargeDensity,
        "C/m^3",
        "charge-density",
        "input",
        "Charge per cubic metre, in the stationary system.",
      ),
      quantity(
        "chargeDensityMoving",
        "Charge density, moving system",
        "\\rho'",
        chargeDensity,
        "C/m^3",
        "charge-density",
        "result",
        "Charge per cubic metre, in the moving system.",
      ),
      quantity(
        "currentDensityStationary",
        "Current density along x, stationary system",
        "J_x",
        currentDensity,
        "A/m^2",
        "current-density",
        "input",
        "The component along the motion of the current per square metre, in the stationary system.",
      ),
      quantity(
        "currentDensityMoving",
        "Current density along x, moving system",
        "J_x'",
        currentDensity,
        "A/m^2",
        "current-density",
        "result",
        "The component along the motion of the current per square metre, in the moving system.",
      ),
      quantity(
        "electronMass",
        "Electron mass",
        "m",
        mass,
        "kg",
        "mass",
        "input",
        "The electron's mass at rest.",
      ),
      quantity(
        "longitudinalForce",
        "Force along the motion",
        "F_x",
        force,
        "N",
        "force",
        "input",
        "The force on the electron along its direction of motion, in the laboratory.",
      ),
      quantity(
        "transverseForceComoving",
        "Sideways force, electron's own frame",
        "F_y'",
        force,
        "N",
        "force",
        "input",
        "The force across the direction of motion, measured in the frame momentarily moving with the electron. The paper's transverse mass uses this force.",
      ),
      quantity(
        "transverseForceLaboratory",
        "Sideways force, laboratory",
        "F_y",
        force,
        "N",
        "force",
        "input",
        "The force across the direction of motion, measured in the laboratory. It is the comoving force divided by gamma.",
      ),
      quantity(
        "accelerationLongitudinalLaboratory",
        "Acceleration along the motion",
        "a_x",
        acceleration,
        "m/s^2",
        "acceleration",
        "result",
        "The electron's acceleration along its direction of motion, in the laboratory.",
      ),
      quantity(
        "accelerationTransverseLaboratory",
        "Sideways acceleration",
        "a_y",
        acceleration,
        "m/s^2",
        "acceleration",
        "result",
        "The electron's acceleration across its direction of motion, in the laboratory.",
      ),
      quantity(
        "velocityComponentXStationary",
        "Velocity along x, stationary system",
        "u_x",
        speed,
        "m/s",
        "velocity-along-x",
        "input",
        "An object's velocity along the direction of the frame change, in the stationary system.",
      ),
      quantity(
        "velocityComponentYStationary",
        "Velocity along y, stationary system",
        "u_y",
        speed,
        "m/s",
        "velocity-along-y",
        "input",
        "An object's velocity across the direction of the frame change, in the stationary system.",
      ),
      quantity(
        "velocityComponentXMoving",
        "Velocity along x, moving system",
        "u_x'",
        speed,
        "m/s",
        "velocity-along-x",
        "result",
        "The same object's velocity along the direction of the frame change, in the moving system.",
      ),
      quantity(
        "velocityComponentYMoving",
        "Velocity along y, moving system",
        "u_y'",
        speed,
        "m/s",
        "velocity-along-y",
        "result",
        "The same object's velocity across the direction of the frame change, in the moving system.",
      ),
      quantity(
        "particleChargeMagnitude",
        "Size of the electron's charge",
        "|q|",
        charge,
        "C",
        "charge-magnitude",
        "input",
        "The magnitude of the electron's charge, the elementary charge; the sign does not enter these relations.",
      ),
      quantity(
        "acceleratingPotential",
        "Accelerating voltage",
        "U",
        potential,
        "V",
        "potential",
        "input",
        "The voltage through which the electron is accelerated from rest.",
      ),
      quantity(
        "kineticEnergy",
        "Kinetic energy",
        "K",
        energy,
        "J",
        "kinetic-energy",
        "result",
        "The electron's energy of motion, m c squared times gamma minus one.",
      ),
      quantity(
        "radiusCurvatureMagnetic",
        "Radius of the circular path",
        "r_B",
        length,
        "m",
        "radius",
        "result",
        "The radius of the circle the electron follows in a uniform magnetic field across its motion.",
      ),
      quantity(
        "magneticFieldStationary",
        "Magnetic field, stationary system",
        "B",
        magneticField,
        "T",
        "magnetic-field",
        "input",
        "The magnetic field in the stationary system. In section 10 it is the strength of a uniform field across the electron's motion; in section 6 a subscript names its component.",
      ),
      quantity(
        "electricFieldStationary",
        "Electric field, stationary system",
        "E",
        electricField,
        "V/m",
        "electric-field",
        "input",
        "The electric field in the stationary system. A subscript names its component: E_y is the component along y.",
      ),
      quantity(
        "electricFieldMoving",
        "Electric field, moving system",
        "E'",
        electricField,
        "V/m",
        "electric-field",
        "result",
        "The electric field in the moving system, component by component.",
      ),
      quantity(
        "magneticFieldMoving",
        "Magnetic field, moving system",
        "B'",
        magneticField,
        "T",
        "magnetic-field",
        "result",
        "The magnetic field in the moving system, component by component.",
      ),
      quantity(
        "clockSpeedStationary",
        "Speed of the transported clock",
        "u",
        speed,
        "m/s",
        "speed",
        "input",
        "The clock's speed at each moment, in the stationary system; u(t) is its value at time t.",
      ),
      quantity(
        "electronSpeedStationary",
        "Electron speed along the way",
        "u",
        speed,
        "m/s",
        "velocity-along-x",
        "input",
        "The electron's speed at an intermediate stage of its acceleration from rest to v: the variable of the work integral.",
      ),
    ].map((q) => [q.id, q]),
  ),
);
