/**
 * Extracted from classic-patents.com
 * Source repository: https://github.com/Dicklesworthstone/classic-patents.com
 * Source path: scripts/e2e-patent-vertical-slices.ts
 * Pinned commit: da11ff475902728fd8dd1d9db9f3af37c16ec8a5
 * License: MIT License (with OpenAI/Anthropic Rider)
 * Preserved license text: /LICENSE
 *
 * Data-driven browser acceptance for one, changed, or every paper vertical
 * slice. This runner does not start or stop a Next server: point it at an
 * existing, unambiguous server with E2E_BASE_URL/--base-url. It preserves
 * all evidence under artifacts/ and emits both JSONL action events and a
 * human summary.
 *
 * Modifications from the donor:
 * - Adapts only the infrastructure this bead's scope table names: browser
 *   launch, viewports, readiness, evidence retention, and JSONL. It carries
 *   no paper scenario source: `buildPatentE2EScenarios` and its
 *   `ScenarioFacts` read the donor's live archival-edition data model
 *   (`allPatents`, `getColorizedEquationsForPatent`,
 *   `CATALOG_CLAIM_CONSTRAINTS`, `PATENT_PHYSICS_REGISTRY`,
 *   `energyChannelsFor`), which has no equivalent here yet. Building the
 *   paper lanes, the DOM readiness contract, and the fixture bundler on this
 *   extracted harness is am-test-e2e-harness-bqmh's scope, not this bead's.
 *   Until that lands, `main` runs a real preflight against the target server
 *   (producing a real JSONL log) and then, outside `--self-test-failure`,
 *   records one honest configuration-failure event naming the missing
 *   scenario source instead of pretending paper scenarios exist.
 * - Removed every patent-domain verification function: `assertPaintedFacsimile`,
 *   `runPatentViewport`, `verifyPinnedPdf`, `verifyFigurePreviewAssets`,
 *   `verifySourceFace`, `verifyClaimNavigation`, `verifyVisualAndTelemetry`,
 *   `verifyPhysicsExplanationSurfaces`, `waitForClaimProbeState`,
 *   `verifyRemainingFaces`, `verifyThemeAndResponsiveState`,
 *   `openAndRestoreFace`, `waitForPatentViewerHydration`,
 *   `waitForVisualSurface`, `controlState`, `selectedClaimNumber`,
 *   `keyboardActionForControl`, `operateControlByPointer`,
 *   `labelForControl`. Their DOM readiness contract (what "hydrated" means,
 *   which stable `data-*` identifiers a face exposes) is am-test-e2e-harness-bqmh's
 *   scope; hard-coding the donor's `dual-projection-viewer` and
 *   `patent-visual-surface` selectors here would misrepresent this bead as
 *   having built the paper reader's DOM contract, which it has not.
 * - Renamed the donor's `runId` (the `RunRecorder`, every emitted event, and
 *   `finishRun`'s summary) to `logRunId`, generated by the shared
 *   `newLogRunId` in scripts/runIds.ts instead of the donor's local
 *   `createRunId`. AGENTS.md "Structured logs" reserves `runId` for an
 *   experiment realization under the runtime contract; this harness is a
 *   test suite, and `logRunId` identifies one execution of it.
 * - Renamed `patentId` to `sliceId` throughout (`RunRecorder`, `CheckContext`,
 *   `meta`, `checked`), matching scripts/e2e/paper-e2e-contract.ts.
 * - `preflightServer`'s product-identity check now looks for "Annus
 *   Mirabilis" instead of "Classic Patents" in the response body; its
 *   same-origin, content-type, and `/_next/` asset-identity checks are
 *   otherwise unchanged.
 * - `USER_AGENT` unchanged: AGENTS.md's "Web Requests" section requires the
 *   same literal user agent string for every request this repository makes.
 * - `RunRecorder`, `captureFailureEvidence`, `inspectFailureEvidence`,
 *   `runFailureEvidenceSelfTest`, `installDiagnostics`, and `formatError`
 *   are otherwise unchanged: they carry no patent-specific assumption, and
 *   together they are the "infrastructure only (browser launch, viewports,
 *   readiness, evidence retention, JSONL)" this bead's scope table names.
 * - Removed `changedPathsFromGit`, `readSmallTextFile`, `checked`, and
 *   `meta`. The donor used the first two to resolve `--changed` against its
 *   live scenario manifest, and `checked`/`meta` to wrap per-check event
 *   emission for that manifest's verification functions; with no paper
 *   scenario source yet (see above), all four would be dead code that only
 *   looked used. `parsePaperE2EArgs` still accepts `--changed` as a CLI
 *   argument in scripts/e2e/paper-e2e-contract.ts; am-test-e2e-harness-bqmh
 *   wires its resolution back in alongside the real scenario source.
 */

import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { type BrowserContext, type ConsoleMessage, chromium, type Page } from "playwright";
import {
  classifyPaperE2EDiagnostic,
  createPaperE2EEvent,
  PAPER_E2E_VIEWPORTS,
  type PaperE2EEvent,
  PaperE2EHelpRequested,
  type PaperE2EOptions,
  type PaperE2ESummary,
  type PaperE2EViewportName,
  paperE2EExitCode,
  paperE2EUsage,
  parsePaperE2EArgs,
  redactPaperE2ESecrets,
  serializePaperE2EEvent,
  stableFailureStem,
  summarizePaperE2EEvents,
} from "./e2e/paper-e2e-contract";
import { newLogRunId } from "./runIds";

// AGENTS.md "Web Requests": every request this repository makes sets this
// user agent, regardless of what it is fetching or why.
const USER_AGENT = "OpenAI File Downloader, XaiImageApiFetch/1.0";
const ACTION_TIMEOUT_MS = 15_000;

interface ScenarioDiagnostics {
  consoleMessages: string[];
  consoleErrors: string[];
  pageErrors: string[];
  networkErrors: string[];
}

interface SelfTestSlice {
  sliceId: string;
  route: string;
}

class RunRecorder {
  readonly events: PaperE2EEvent[] = [];
  readonly runDirectory: string;
  readonly eventPath: string;
  private readonly diagnosticsByScenario = new Map<string, ScenarioDiagnostics>();

  constructor(
    readonly logRunId: string,
    outputRoot: string,
  ) {
    this.runDirectory = path.resolve(outputRoot, logRunId);
    this.eventPath = path.join(this.runDirectory, "events.jsonl");
    fs.mkdirSync(this.runDirectory, { recursive: true });
  }

  registerDiagnostics(
    sliceId: string,
    viewport: PaperE2EViewportName,
    diagnostics: ScenarioDiagnostics,
  ) {
    this.diagnosticsByScenario.set(`${sliceId}::${viewport}`, diagnostics);
  }

  emit(event: Omit<PaperE2EEvent, "schemaVersion" | "sequence" | "timestamp">): PaperE2EEvent {
    const diagnostics = this.diagnosticsByScenario.get(`${event.sliceId}::${event.viewport}`);
    const complete = createPaperE2EEvent({
      ...event,
      sequence: this.events.length + 1,
      consoleErrors: event.consoleErrors ?? diagnostics?.consoleErrors ?? [],
      pageErrors: event.pageErrors ?? diagnostics?.pageErrors ?? [],
      networkErrors: event.networkErrors ?? diagnostics?.networkErrors ?? [],
    });
    this.events.push(complete);
    fs.appendFileSync(this.eventPath, `${serializePaperE2EEvent(complete)}\n`, "utf8");
    const marker =
      complete.status === "pass" ? "PASS" : complete.status === "fail" ? "FAIL" : "INFO";
    console.log(
      `[${marker}] ${complete.sliceId} ${complete.viewport} ${complete.face}/${complete.action} (${complete.durationMs}ms)`,
    );
    return complete;
  }

  writeSummary(summary: PaperE2ESummary): string {
    const summaryPath = path.join(this.runDirectory, "summary.json");
    fs.writeFileSync(summaryPath, `${JSON.stringify(summary, null, 2)}\n`, "utf8");
    return summaryPath;
  }
}

export async function main() {
  let options: PaperE2EOptions;
  try {
    options = parsePaperE2EArgs(process.argv.slice(2));
  } catch (error) {
    if (error instanceof PaperE2EHelpRequested) {
      console.log(paperE2EUsage());
      return;
    }
    console.error(error instanceof Error ? error.message : String(error));
    console.error(`\n${paperE2EUsage()}`);
    process.exitCode = 2;
    return;
  }

  const startedAt = new Date().toISOString();
  const recorder = new RunRecorder(newLogRunId(), options.outputRoot);

  try {
    await preflightServer(options.baseUrl, recorder);
  } catch {
    finishRun(recorder, {
      startedAt,
      baseUrl: options.baseUrl,
      sliceIds: [],
      viewports: options.viewports,
    });
    return;
  }

  if (!options.selfTestFailure) {
    recordRunConfigurationFailure(
      recorder,
      new Error(
        "Paper vertical-slice scenarios are not wired in yet; see am-test-e2e-harness-bqmh, which builds the " +
          "paper lanes, the DOM readiness contract, and the fixture bundler on this extracted harness. " +
          "Run with --self-test-failure to exercise the failure-evidence retention path.",
      ),
    );
    finishRun(recorder, {
      startedAt,
      baseUrl: options.baseUrl,
      sliceIds: [],
      viewports: options.viewports,
    });
    return;
  }

  console.log("=======================================================================");
  console.log("  Annus Mirabilis paper vertical-slice E2E acceptance");
  console.log(`  Target: ${options.baseUrl}`);
  console.log("  Mode: intentional failure-evidence self-test");
  console.log(`  Structured log: ${recorder.eventPath}`);
  console.log("=======================================================================");

  let browser: Awaited<ReturnType<typeof chromium.launch>>;
  try {
    browser = await chromium.launch({ headless: !options.headed });
  } catch (error) {
    recorder.emit({
      logRunId: recorder.logRunId,
      sliceId: "__run__",
      route: "/",
      viewport: "run",
      face: "runtime",
      action: "browser-launch",
      status: "fail",
      durationMs: 0,
      expected: "a runnable Playwright Chromium installation",
      errors: [error instanceof Error ? error.message : String(error)],
    });
    finishRun(recorder, {
      startedAt,
      baseUrl: options.baseUrl,
      sliceIds: [],
      viewports: options.viewports,
    });
    return;
  }
  try {
    await runFailureEvidenceSelfTest({ browser, baseUrl: options.baseUrl, recorder });
  } catch (error) {
    recorder.emit({
      logRunId: recorder.logRunId,
      sliceId: "__run__",
      route: "/",
      viewport: "run",
      face: "runtime",
      action: "browser-run",
      status: "fail",
      durationMs: 0,
      errors: [formatError(error)],
    });
  } finally {
    try {
      await browser.close();
    } finally {
      finishRun(recorder, {
        startedAt,
        baseUrl: options.baseUrl,
        sliceIds: [],
        viewports: options.viewports,
      });
    }
  }
}

async function runFailureEvidenceSelfTest(args: {
  browser: Awaited<ReturnType<typeof chromium.launch>>;
  baseUrl: string;
  recorder: RunRecorder;
}) {
  const scenario: SelfTestSlice = { sliceId: "__harness-self-test__", route: "/" };
  const viewport = "desktop" as const;
  const context = await args.browser.newContext({
    viewport: PAPER_E2E_VIEWPORTS[viewport],
    deviceScaleFactor: 1,
    reducedMotion: "no-preference",
    userAgent: USER_AGENT,
    extraHTTPHeaders: { "x-annus-mirabilis-e2e": args.recorder.logRunId },
  });
  await context.tracing.start({ screenshots: true, snapshots: true, sources: true });
  const page = await context.newPage();
  page.setDefaultTimeout(ACTION_TIMEOUT_MS);
  const diagnostics: ScenarioDiagnostics = {
    consoleMessages: [],
    consoleErrors: [],
    pageErrors: [],
    networkErrors: [],
  };
  installDiagnostics(page, diagnostics);
  const started = performance.now();
  let traceStopped = false;

  try {
    const response = await page.goto(args.baseUrl, {
      waitUntil: "domcontentloaded",
      timeout: 30_000,
    });
    const responseStatus = response?.status() ?? 0;
    const artifactPaths = await captureFailureEvidence({
      page,
      context,
      recorder: args.recorder,
      scenario,
      viewport,
      diagnostics,
    });
    const evidenceIntegrity = inspectFailureEvidence(artifactPaths);
    traceStopped = true;
    args.recorder.emit({
      logRunId: args.recorder.logRunId,
      sliceId: scenario.sliceId,
      route: scenario.route,
      viewport,
      face: "self-test",
      action: "synthetic-failure",
      status: "fail",
      durationMs: performance.now() - started,
      expected: {
        result: "intentional nonzero exit",
        evidenceKinds: ["screenshot", "DOM", "diagnostics", "trace"],
      },
      actual: {
        responseStatus,
        url: page.url(),
        artifactCount: artifactPaths.length,
        evidenceIntegrity,
      },
      responseStatus,
      errors: ["Synthetic failure requested by --self-test-failure."],
      consoleErrors: diagnostics.consoleErrors,
      pageErrors: diagnostics.pageErrors,
      networkErrors: diagnostics.networkErrors,
      artifactPaths,
    });
    args.recorder.emit({
      logRunId: args.recorder.logRunId,
      sliceId: scenario.sliceId,
      route: scenario.route,
      viewport,
      face: "self-test",
      action: "failure-evidence-integrity",
      status: evidenceIntegrity.valid ? "info" : "fail",
      durationMs: 0,
      expected: "nonempty screenshot, DOM, diagnostics, and trace artifacts",
      actual: evidenceIntegrity,
      errors: evidenceIntegrity.valid ? undefined : evidenceIntegrity.problems,
      artifactPaths,
    });
  } finally {
    if (!traceStopped) await context.tracing.stop().catch(() => undefined);
    await page.close().catch(() => undefined);
    await context.close();
  }
}

async function captureFailureEvidence(args: {
  page: Page;
  context: BrowserContext;
  recorder: RunRecorder;
  scenario: SelfTestSlice;
  viewport: PaperE2EViewportName;
  diagnostics: ScenarioDiagnostics;
}): Promise<string[]> {
  const stem = stableFailureStem(args.scenario.sliceId, args.viewport, "run", "failure");
  const base = path.join(args.recorder.runDirectory, stem);
  const screenshotPath = `${base}.png`;
  const domPath = `${base}.html`;
  const diagnosticsPath = `${base}.diagnostics.json`;
  const tracePath = `${base}.trace.zip`;
  const paths: string[] = [];

  if (
    await args.page
      .screenshot({ path: screenshotPath, fullPage: true })
      .then(() => true)
      .catch(() => false)
  ) {
    paths.push(screenshotPath);
  }
  const dom = await args.page.content().catch(() => undefined);
  if (dom !== undefined) {
    fs.writeFileSync(domPath, redactPaperE2ESecrets(dom), "utf8");
    paths.push(domPath);
  }
  const redactedDiagnostics = {
    url: redactPaperE2ESecrets(args.page.url()),
    consoleMessages: args.diagnostics.consoleMessages.map(redactPaperE2ESecrets),
    consoleErrors: args.diagnostics.consoleErrors.map(redactPaperE2ESecrets),
    pageErrors: args.diagnostics.pageErrors.map(redactPaperE2ESecrets),
    networkErrors: args.diagnostics.networkErrors.map(redactPaperE2ESecrets),
  };
  fs.writeFileSync(diagnosticsPath, `${JSON.stringify(redactedDiagnostics, null, 2)}\n`, "utf8");
  paths.push(diagnosticsPath);
  if (
    await args.context.tracing
      .stop({ path: tracePath })
      .then(() => true)
      .catch(() => false)
  ) {
    paths.push(tracePath);
  }
  return paths;
}

function inspectFailureEvidence(paths: readonly string[]) {
  const expected = {
    screenshot: /\.png$/,
    domSnapshot: /\.html$/,
    diagnostics: /\.diagnostics\.json$/,
    trace: /\.trace\.zip$/,
  } as const;
  const artifacts = Object.fromEntries(
    Object.entries(expected).map(([kind, matcher]) => {
      const artifactPath = paths.find((candidate) => matcher.test(candidate));
      let bytes = 0;
      if (artifactPath) {
        try {
          bytes = fs.statSync(artifactPath).size;
        } catch {
          bytes = 0;
        }
      }
      return [kind, { path: artifactPath ?? null, bytes, nonempty: bytes > 0 }];
    }),
  );
  const problems = Object.entries(artifacts)
    .filter(([, artifact]) => !artifact.nonempty)
    .map(([kind]) => `Missing or empty ${kind} failure artifact.`);
  return { valid: problems.length === 0, artifacts, problems };
}

async function preflightServer(baseUrl: string, recorder: RunRecorder) {
  const started = performance.now();
  try {
    const response = await fetch(baseUrl, {
      headers: { "User-Agent": USER_AGENT },
      signal: AbortSignal.timeout(ACTION_TIMEOUT_MS),
    });
    const text = await response.text();
    const requestedUrl = new URL(baseUrl);
    const finalUrl = new URL(response.url);
    const contentType = response.headers.get("content-type");
    const hasProductIdentity = text.includes("Annus Mirabilis");
    const hasNextAssetIdentity = text.includes("/_next/");
    if (
      response.status !== 200 ||
      finalUrl.origin !== requestedUrl.origin ||
      !contentType?.includes("text/html") ||
      !hasProductIdentity ||
      !hasNextAssetIdentity
    ) {
      throw new Error(
        `E2E target is not an unambiguous Annus Mirabilis Next server: status=${response.status}, requestedOrigin=${requestedUrl.origin}, finalOrigin=${finalUrl.origin}, contentType=${contentType ?? "missing"}, productIdentity=${String(hasProductIdentity)}, nextAssetIdentity=${String(hasNextAssetIdentity)}.`,
      );
    }
    const htmlSha256 = createHash("sha256").update(text).digest("hex");
    recorder.emit({
      logRunId: recorder.logRunId,
      sliceId: "__run__",
      route: "/",
      viewport: "run",
      face: "preflight",
      action: "target-identity",
      status: "pass",
      durationMs: performance.now() - started,
      expected: "same-origin Annus Mirabilis Next HTML with HTTP 200 and recorded build identity",
      actual: {
        status: response.status,
        finalUrl: response.url,
        server: response.headers.get("server"),
        contentType,
        etag: response.headers.get("etag"),
        lastModified: response.headers.get("last-modified"),
        htmlBytes: Buffer.byteLength(text),
        htmlSha256,
      },
      responseStatus: response.status,
    });
  } catch (error) {
    recorder.emit({
      logRunId: recorder.logRunId,
      sliceId: "__run__",
      route: "/",
      viewport: "run",
      face: "preflight",
      action: "target-identity",
      status: "fail",
      durationMs: performance.now() - started,
      expected: "same-origin Annus Mirabilis Next HTML with HTTP 200 and recorded build identity",
      errors: [error instanceof Error ? error.message : String(error)],
    });
    throw error;
  }
}

function recordRunConfigurationFailure(recorder: RunRecorder, error: unknown) {
  recorder.emit({
    logRunId: recorder.logRunId,
    sliceId: "__run__",
    route: "/",
    viewport: "run",
    face: "configuration",
    action: "scenario-selection",
    status: "fail",
    durationMs: 0,
    expected: "a valid non-empty scenario selection backed by pinned content",
    errors: [error instanceof Error ? error.message : String(error)],
  });
}

function finishRun(
  recorder: RunRecorder,
  args: {
    startedAt: string;
    baseUrl: string;
    sliceIds: readonly string[];
    viewports: readonly PaperE2EViewportName[];
  },
) {
  const summary = summarizePaperE2EEvents({
    logRunId: recorder.logRunId,
    startedAt: args.startedAt,
    finishedAt: new Date().toISOString(),
    baseUrl: args.baseUrl,
    selectedSlices: args.sliceIds,
    selectedViewports: args.viewports,
    artifactDirectory: recorder.runDirectory,
    events: recorder.events,
  });
  const summaryPath = recorder.writeSummary(summary);
  console.log("=======================================================================");
  console.log(
    `  Completed: ${summary.passedActions} passed actions, ${summary.failedActions} failed actions`,
  );
  console.log(`  Failed slices: ${summary.failedSlices.join(", ") || "none"}`);
  for (const group of summary.actionGroups.filter((entry) => entry.failedActions > 0)) {
    console.log(
      `  Failure group: ${group.sliceId} ${group.viewport} ${group.face}/${group.action} (${group.failedActions}/${group.eventCount})`,
    );
    if (group.artifactPaths.length > 0) {
      console.log(`    Evidence: ${group.artifactPaths.join(", ")}`);
    }
  }
  console.log(`  JSONL events: ${recorder.eventPath}`);
  console.log(`  Summary: ${summaryPath}`);
  console.log("=======================================================================");
  process.exitCode = paperE2EExitCode(summary);
}

function installDiagnostics(page: Page, diagnostics: ScenarioDiagnostics) {
  page.on("console", (message: ConsoleMessage) => {
    diagnostics.consoleMessages.push(`[${message.type()}] ${message.text()}`);
    if (message.type() === "error") diagnostics.consoleErrors.push(`[console] ${message.text()}`);
  });
  page.on("pageerror", (error) => diagnostics.pageErrors.push(`[pageerror] ${error.message}`));
  page.on("response", (response) => {
    if (response.status() >= 400) {
      diagnostics.networkErrors.push(`[http ${response.status()}] ${response.url()}`);
    }
  });
  page.on("requestfailed", (request) => {
    diagnostics.networkErrors.push(
      `[requestfailed] ${request.method()} ${request.url()} ${request.failure()?.errorText ?? "unknown"}`,
    );
  });
}

function formatError(error: unknown): string {
  if (!(error instanceof Error)) return String(error);
  if (!error.stack) return error.message;
  return error.stack.includes(error.message) ? error.stack : `${error.message}\n${error.stack}`;
}

const isMainModule =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);

if (isMainModule) {
  main().catch((error) => {
    console.error("Paper vertical-slice E2E failed:", error);
    process.exitCode = 1;
  });
}
