#!/usr/bin/env bun
/**
 * Generates src/generated/quantity-labels.ts: a client-safe id -> plain-word-name map
 * built from the canonical quantity registry (am-not-quantity-registry-2f7).
 *
 * Why this exists: the registry itself loads content/quantities/*.yaml off disk through
 * `new URL(..., import.meta.url)`, so it is server-only. Tour presentation needs those
 * plain-word names inside a "use client" module (the PresentationProvider renders under
 * ReaderController, which is a Client Component), and a client bundle cannot reach the
 * filesystem. Importing the registry from that module made `next build` fail outright.
 *
 * The generated map carries only `id -> name` — the one field tour mode consumes — so no
 * dimension/schema machinery is pulled into the client bundle.
 *
 * With --check, validates that the committed/generated file is fresh without writing,
 * matching the --check convention of scripts/generate-quantity-ids.ts.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadQuantityRegistry } from "../src/content/quantities/registry.ts";

const ROOT = resolve(fileURLToPath(new URL("../", import.meta.url)));
const OUT_PATH = resolve(ROOT, "src/generated/quantity-labels.ts");

export function renderQuantityLabels(pairs: readonly (readonly [string, string])[]): string {
  const body = pairs.map(([id, name]) => `  ${JSON.stringify(id)}: ${JSON.stringify(name)},`);
  return [
    "// Generated by scripts/generate-quantity-labels.ts; do not edit.",
    "// Source of truth: content/quantities/*.yaml via the canonical quantity registry.",
    "",
    "/** Plain-word name for every registered quantity id. Client-safe: data only. */",
    "export const QUANTITY_LABELS: Readonly<Record<string, string>> = Object.freeze({",
    ...body,
    "});",
    "",
  ].join("\n");
}

function main(argv: readonly string[]): number {
  const check = argv.includes("--check");
  const registry = loadQuantityRegistry();
  const pairs = [...registry.quantities.entries()]
    .map(([id, q]) => [id, q.name] as const)
    .sort((a, b) => a[0].localeCompare(b[0]));

  const rendered = renderQuantityLabels(pairs);

  if (check) {
    if (!existsSync(OUT_PATH)) {
      console.error(
        `[quantity-labels] ${OUT_PATH} is missing; run bun scripts/generate-quantity-labels.ts`,
      );
      return 1;
    }
    if (readFileSync(OUT_PATH, "utf8") !== rendered) {
      console.error(
        "[quantity-labels] generated file is stale; run bun scripts/generate-quantity-labels.ts",
      );
      return 1;
    }
    return 0;
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, rendered);
  console.log(JSON.stringify({ event: "quantity-labels-generated", quantities: pairs.length }));
  return 0;
}

if (import.meta.main) {
  process.exit(main(process.argv.slice(2)));
}
