import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BM05_DEFAULTS } from "../src/experiments/bm05/definition.ts";
import { encodeResult } from "../src/experiments/results/codec.ts";
import { hashSnapshotFunction } from "./snapshotFunctionHash.mjs";
import { createBm05Recording, measureBm05 } from "../src/workers/operations/bm05.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SNAPSHOT_FUNCTION = {
  exportName: "kernelDiffusivity",
  filePath: "src/physics/reference/diffusion/walkLaws.ts",
};
/** Hash the actual local import closure, including type contracts and this generator. */
export async function evaluatorSources() {
  const seen = new Map();
  async function visit(path) {
    if (seen.has(path)) return;
    const source = await readFile(resolve(root, path), "utf8");
    seen.set(path, source);
    for (const match of source.matchAll(/(?:from\s*|import\s*)["'](\.[^"']+)["']/g)) {
      const target = relative(root, resolve(root, dirname(path), match[1]));
      if (target.startsWith("../") || !/\.(ts|mjs)$/.test(target))
        throw new Error(`Unhashable evaluator dependency: ${target}`);
      await visit(target);
    }
  }
  await visit("src/workers/host/bm05Host.ts");
  seen.set(
    "scripts/generate-walks.mjs",
    await readFile(resolve(root, "scripts/generate-walks.mjs"), "utf8"),
  );
  return [...seen].sort(([a], [b]) => a.localeCompare(b, "en"));
}
export async function generateLab() {
  const sources = await evaluatorSources();
  const hash = createHash("sha256");
  for (const [path, text] of sources)
    hash.update(`${path}\0${Buffer.byteLength(text)}\0`).update(text);
  const sourceDigest = `source:sha256:${hash.digest("hex")}`;
  const recording = await createBm05Recording(BM05_DEFAULTS, { yieldControl: async () => {} });
  if (recording.kind !== "accepted") throw new Error("The static walk recording failed.");
  const evaluated = await measureBm05(recording.data, BM05_DEFAULTS, false);
  if (evaluated.kind !== "accepted")
    throw new Error("The static worked example did not evaluate successfully.");
  const example = {
    sourceDigest,
    snapshotFunctionName: SNAPSHOT_FUNCTION.exportName,
    snapshotFunctionHash: await hashSnapshotFunction(root, SNAPSHOT_FUNCTION),
    parameters: BM05_DEFAULTS,
    stepIndex: evaluated.data.stepIndex,
    simulationTime: evaluated.data.simulationTime,
    results: evaluated.data.outputs.map(encodeResult),
  };
  await mkdir(resolve(root, "src/generated"), { recursive: true });
  await writeFile(
    resolve(root, "src/generated/bm05-example.json"),
    `${JSON.stringify(example, null, 2)}\n`,
  );
  await writeFile(
    resolve(root, "src/generated/bm05-provenance.ts"),
    `// Generated by scripts/generate-walks.mjs; do not edit.\nexport const BM05_SOURCE_DIGEST = ${JSON.stringify(sourceDigest)};\n`,
  );
  await writeFile(
    resolve(root, "src/generated/bm05-sources.json"),
    `${JSON.stringify({ sourceDigest, files: sources.map(([path]) => path) }, null, 2)}\n`,
  );
  return { sourceDigest, files: sources.length };
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  console.log(JSON.stringify(await generateLab()));
